name: Deploy to Aliyun

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REMOTE_HOST: 8.140.239.170
      REMOTE_USER: abinzhao
      REMOTE_DIR: /var/node-service-app/hm-admin-node

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.ALIYUN_SSH_PRIVATE_KEY }}

      - name: Deploy to Aliyun
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} \
            "cd ${{ env.REMOTE_DIR }} && \
             git pull && \
             pnpm install && \
             pm2 reload ecosystem.config.js --env production"